import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  menu: [
    {
      id: 'detskii-menu',
      title: 'Детское меню',
      level: 1,
      children: [
        {
          id: 'detskii-menusalaty',
          title: 'Салаты',
          level: 2,
          children: [
            {
              id: 'salat-ovoshnyi',
              title: 'САЛАТ ОВОЩНОЙ',
              price: '300',
            },
            {
              id: 'salat-olivie',
              title: 'САЛАТ ОЛИВЬЕ',
              price: '300',
            },
            {
              id: 'salat-cezar',
              title: 'САЛАТ ЦЕЗАРЬ С КУРИЦЕЙ',
              price: '450',
            },
          ],
        },
        {
          id: 'detskii-menusupy',
          title: 'Супы',
          level: 2,
          children: [
            {
              id: 'bulyon-hinkali',
              title: 'БУЛЬОН С БЭЙБИ-ХИНКАЛИ',
              price: '300',
            },
            {
              id: 'sup-frikadelki',
              title: 'СУП С ФРИКАДЕЛЬКАМИ',
              price: '250',
            },
            {
              id: 'borsch',
              title: 'БОРЩ СО СМЕТАНОЙ',
              price: '450',
            },
          ],
        },
        {
          id: 'detskii-menugoryachie-blyuda',
          title: 'Горячие блюда',
          level: 2,
          children: [
            {
              id: 'pasta-arabiata',
              title: 'ПАСТА АРАБЬЯТА',
              price: '360',
            },
            {
              id: 'pasta-slivki',
              title: 'ПАСТА В СЛИВОЧНОМ СОУСЕ',
              price: '470',
            },
            {
              id: 'kurinii-shashlychok',
              title: 'КУРИНЫЙ ШАШЛЫЧОК НА ШПАЖКЕ',
              price: '480',
            },
            {
              id: 'kotletki-kuritsa',
              title: 'КОТЛЕТКИ ИЗ КУРИЦЫ',
              price: '370',
            },
            {
              id: 'makaroni-s-syrom',
              title: 'ДЕТСКИЕ МАКАРОНЫ С СЫРОМ',
              price: '390',
            },
            {
              id: 'hinkali-kuritsa',
              title: 'БЭЙБИ-ХИНКАЛИ ИЗ КУРИЦЫ',
              price: '490',
            },
            {
              id: 'hachapuri-adjarski',
              title: 'БЭЙБИ-ХАЧАПУРИ ПО-АДЖАРСКИ',
              price: '300',
            },
            {
              id: 'hachapuri-imeretinski',
              title: 'БЭЙБИ-ХАЧАПУРИ ПО-ИМЕРЕТИНСКИ',
              price: '300',
            },
            {
              id: 'hachapuri-megreliski',
              title: 'БЭЙБИ-ХАЧАПУРИ ПО-МЕГРЕЛЬСКИ',
              price: '300',
            },
          ],
        },
        {
          id: 'detskii-menugarniry',
          title: 'Гарниры',
          level: 2,
          children: [
            {
              id: 'kartofel-fri',
              title: 'КАРТОФЕЛЬ ФРИ',
              price: '210',
            },
            {
              id: 'kartofel-puree',
              title: 'КАРТОФЕЛЬНОЕ ПЮРЕ',
              price: '150',
            },
            {
              id: 'ris-otvarnoi',
              title: 'РИС ОТВАРНОЙ',
              price: '170',
            },
          ],
        },
      ],
    },
    {
      title: 'ЗАВТРАКИ',
      id: 'breakfast',
      level: 1,
      children: [
        {
          id: 'kasha-ovsyanaia',
          title: 'Каша овсяная',
          mass: '300 г',
          price: '350',
        },
        {
          id: 'kasha-risovaia-s-toppingom',
          title: 'Каша рисовая с топпингом',
          mass: '300 г',
          price: '430',
        },
        {
          id: 'shakshuka',
          title: 'Шакшука',
          mass: '250 г',
          price: '680',
        },
        {
          id: 'glazunia',
          title: 'Глазунья',
          mass: '120 г',
          price: '350',
        },
        {
          id: 'omlet',
          title: 'Омлет',
          mass: '150 г',
          price: '360',
        },
        {
          id: 'topping-na-vybor',
          title: 'Дополнительно топпинг на выбор',
          mass: '0',
          price: '130',
        },
        {
          id: 'blinchiki-s-syrom',
          title: 'Блинчики с сыром',
          mass: '3 шт',
          price: '390',
        },
        {
          id: 'blinchiki-s-myasom',
          title: 'Блинчики с мясом',
          mass: '3 шт',
          price: '580',
        },
        {
          id: 'blinchiki-s-tvorogom',
          title: 'Блинчики с творогом',
          mass: '2 шт',
          price: '490',
        },
        {
          id: 'syrniki',
          title: 'Сырники',
          mass: '3 шт',
          price: '450',
        },
        {
          id: 'khinkali-s-klubnikoi',
          title: 'Хинкали с клубникой',
          mass: '3 шт / 300 г',
          price: '380',
        },
        {
          id: 'khinkali-s-vishnei',
          title: 'Хинкали с вишней',
          mass: '3 шт / 300 г',
          price: '360',
        },
      ],
    },
    {
      title: 'ХОЛОДНЫЕ ЗАКУСКИ',
      id: 'cold-dishes',
      level: 1,
      children: [
        {
          id: 'assorti-phali',
          title: 'Ассорти пхали',
          mass: '160 г',
          price: '570',
        },
        // {
        //   id: 'phali-iz-svekly',
        //   title: 'Пхали из свеклы',
        //   mass: '160 г',
        //   price: '310',
        // },
        // {
        //   id: 'phali-iz-zelenoi-fasoli',
        //   title: 'Пхали из зелёной фасоли',
        //   mass: '160 г',
        //   price: '420',
        // },
        // {
        //   id: 'phali-iz-shpinata',
        //   title: 'Пхали из шпината',
        //   mass: '160 г',
        //   price: '540',
        // },
        {
          id: 'baklazhany-zharennye-s-gretskim-orekhom',
          title: 'Баклажаны жаренные с грецким орехом',
          mass: '160 г',
          price: '760',
        },
        {
          id: 'adjapsandali',
          title: 'Аджапсандали',
          mass: '230 г',
          price: '890',
        },
        // {
        //   id: 'lobio-s-gretskimi-orekhami',
        //   title: 'Лобио с грецкими орехами',
        //   mass: '200 г',
        //   price: '350',
        // },
        {
          id: 'satsivi-iz-kuritsy',
          title: 'Сациви из курицы',
          mass: '240 г',
          price: '780',
        },
        {
          id: 'syr-suluguni-imetinskii',
          title: 'Сыр Сулугуни / Имеретинский',
          mass: '150 г',
          price: '390',
        },
        {
          id: 'assorti-domashnikh-soleniy',
          title: 'Ассорти домашних солений',
          mass: '360 г',
          price: '520',
        },
        {
          id: 'assorti-ovoshchnoe',
          title: 'Ассорти овощное',
          mass: '350 г',
          price: '1070',
        },
        {
          id: 'seld-s-kartofelem',
          title: 'Сельдь с картофелем',
          mass: '240 г',
          price: '410',
        },
        {
          id: 'seld-s-kartofelem',
          title: 'Сельдь с картофелем',
          mass: '240 г',
          price: '370',
        },
        {
          id: 'semga-slabosolenaya',
          title: 'Сёмга слабосолёная',
          mass: '150 г',
          price: '1580',
        },
        {
          id: 'yazyk-govyazhiy',
          title: 'Язык говяжий',
          mass: '150 г',
          price: '980',
        },
        {
          id: 'tadjasskie-olivki-masliny',
          title: 'Таджасские оливки / маслины',
          mass: '50 г',
          price: '390',
        },
        // {
        //   id: 'siomga-slabosolionaia',
        //   title: 'Сёмга слабосолёная',
        //   mass: '150 г',
        //   price: '870',
        // },
        // {
        //   id: 'yazyk-goviazhi',
        //   title: 'Язык говяжий',
        //   mass: '150 г',
        //   price: '690',
        // },
        // {
        //   id: 'tadzhaski-olivki-masl',
        //   title: 'Таджаски оливки / маслины',
        //   mass: '50 г',
        //   price: '440',
        // },
      ],
    },
    {
      title: 'САЛАТЫ',
      id: 'salads',
      level: 1,
      children: [
        {
          id: 'ovoshchnoi-salat-s-kakhetinskim-maslom',
          title: 'Овощной салат с кахетинским маслом',
          mass: '230 г',
          price: '580',
        },
        {
          id: 'ovoshchnoi-salat-po-gruzinski-s-gretskim-orekhom',
          title: 'Овощной салат по-грузински с грецким орехом',
          mass: '240 г',
          price: '640',
        },

        {
          id: 'sladkie-pomidory-s-krasnym-lukom-i-suluguni',
          title: 'Сладкие помидоры с красным луком и Сулугуни',
          mass: '240 г',
          price: '760',
        },
        {
          id: 'hrustashchie-baklazhany-s-tomatami',
          title: 'Хрустящие баклажаны с томатами',
          mass: '220 г',
          price: '690',
        },
        {
          id: 'olivie-s-yazykom',
          title: 'Оливье с курицей',
          mass: '180 г',
          price: '510',
        },
        {
          id: 'ovoschnoi-salat-po-domashnemu',
          title: 'Овощной салат по-домашнему',
          mass: '230 г',
          price: '710',
        },
        // {
        //   id: 'salat-so-slabosolenoi-siomgoi',
        //   title: 'Салат со слабосоленой сёмгой',
        //   mass: '210 г',
        //   price: '1190',
        // },
        {
          id: 'salat-iz-svezhei-kapusty',
          title: 'Салат из свежей капусты',
          mass: '150 г',
          price: '250',
        },
        {
          id: 'tsezar-s-kuritsei',
          title: 'Цезарь с курицей по-грузински',
          mass: '220 г',
          price: '650',
        },
      ],
    },
    {
      id: 'goryachie-zakuski',
      title: 'Горячие закуски',
      level: 1,
      children: [
        {
          id: 'dolma-iz-telyatiny',
          title: 'Долма из телятины в виноградных листьях',
          mass: '250 г',
          price: '690',
        },
        {
          id: 'shampinony-s-syrom-suluguni',
          title: 'ХИТ Шампиньоны с сыром Сулугуни на кеци',
          mass: '250 г',
          price: '560',
        },
        {
          id: 'lobio-po-megrelski',
          title: 'Лобио по-мегрельски с гурийской капустой',
          mass: '450 г',
          price: '690',
        },
        {
          id: 'ovoshchi-s-syrom-suluguni',
          title: 'ХИТ Овощи с сыром Сулугуни на кеци',
          mass: '400 г',
          price: '790',
        },
        {
          id: 'shariki-elardzhi',
          title: 'Шарики Эларджи с соусом Баже',
          mass: '200 г',
          price: '430',
        },
        {
          id: 'kuchmachi-iz-govyadiny',
          title: 'Кучмачи из говядины на кеци',
          mass: '200 г',
          price: '690',
        },
        {
          id: 'zharenyi-syr-suluguni',
          title: 'Жареный сыр Сулугуни',
          mass: '250 г',
          price: '510',
        },
        {
          id: 'mamaliga-s-syrom-suluguni',
          title: 'Мамалыга с сыром Сулугуни на кеци',
          mass: '250 г',
          price: '420',
        },
        {
          id: 'elardzhi-na-ketsi',
          title: 'Эларджи на кеци',
          mass: '250 г',
          price: '480',
        },
      ],
    },
    {
      id: 'hinkali',
      title: 'ХИНКАЛИ',
      level: 1,
      children: [
        {
          id: 'khinkali-s-baraninoi',
          title: 'Хинкали с бараниной',
          mass: '3 шт | 320 г',
          price: '450',
        },
        {
          id: 'khinkali-s-goviadinoy',
          title: 'Хинкали с говядиной',
          mass: '3 шт | 320 г',
          price: '450',
        },
        {
          id: 'khinkali-s-syrom-suluguni',
          title: 'Хинкали с сыром Сулугуни',
          mass: '3 шт | 280 г',
          price: '420',
        },
      ],
    },
    {
      id: 'suppes',
      title: 'СУПЫ',
      level: 1,
      children: [
        {
          id: 'sup-harcho',
          title: 'Суп Харчо',
          mass: '300 г',
          price: '570',
        },
        {
          id: 'navaristy-bulon-s-mini-khinkali',
          title: 'Наваристый бульон с мини-хинкали',
          mass: '300 г',
          price: '360',
        },
        {
          id: 'sup-rybnyi-po-gruzinski',
          title: 'Суп рыбный по-грузински',
          mass: '300 г',
          price: '1390',
        },
        {
          id: 'borsch-s-goviadinoy',
          title: 'Борщ с говядиной',
          mass: '300 г',
          price: '640',
        },
        {
          id: 'sup-s-lapshoi-iz-fermerskoy-kuritsy',
          title: 'Суп с лапшой из фермерской курицы',
          mass: '300 г',
          price: '490',
        },
        // {
        //   id: 'solyanka-sbornaya-myasnaya',
        //   title: 'Солянка сборная мясная',
        //   mass: '300 г',
        //   price: '860',
        // },
      ],
    },
    {
      id: 'hot-meat-dishes',
      title: 'ГОРЯЧИЕ МЯСНЫЕ БЛЮДА',
      level: 1,
      children: [
        {
          id: 'khinkali-s-baraninoi',
          title: 'Хинкали с бараниной',
          mass: '3 шт | 320 г',
          price: '450',
        },
        {
          id: 'khinkali-s-goviadinoy',
          title: 'Хинкали с говядиной',
          mass: '3 шт | 320 г',
          price: '450',
        },
        {
          id: 'khinkali-s-syrom-suluguni',
          title: 'Хинкали с сыром Сулугуни',
          mass: '3 шт | 280 г',
          price: '390',
        },
        {
          id: 'deda-khinkali',
          title: 'Деда Хинкали',
          mass: '700 г',
          price: '1290',
        },
        {
          id: 'khinkali1',
          title: 'Хинкали',
          mass: '1 шт',
          price: '150',
        },
        {
          id: 'chakhokhbili',
          title: 'Чахохбили на кеци',
          mass: '350 г',
          price: '790',
        },
        {
          id: 'odzhakhuri-s-kuritsey',
          title: 'Оджахури с курицей',
          mass: '320 г',
          price: '860',
        },
        {
          id: 'chashushuli-iz-telyatiny',
          title: 'Чашушули из телятины',
          mass: '300 г',
          price: '860',
        },
        {
          id: 'odzhakhuri-s-baraninoy',
          title: 'Оджахури с бараниной на кеци',
          mass: '320 г',
          price: '1170',
        },
        // {
        //   id: 'kharcho-po-megrelski-s-tsyplenkom',
        //   title: 'Харчо по-мегрельски с цыпленком',
        //   mass: '440 г',
        //   price: '850',
        // },
        {
          id: 'odzhakhuri-iz-telyatiny-na-keci',
          title: 'Оджахури из говяжьей вырезки на кеци',
          mass: '320 г',
          price: '1590',
        },
        {
          id: 'chanahi-iz-baraniny-v-gorshochke',
          title: 'Чанахи с бараниной в горшочке',
          mass: '400 г',
          price: '1760',
        },
        // {
        //   id: 'perepelka-s-elardzhi',
        //   title: 'Перепелка с эларджи',
        //   mass: '350 г',
        //   price: '1570',
        // },
        {
          id: 'tsyplenyok-chkmeruli-na-keci',
          title: 'Цыплёнок Чкмерули на кеци',
          mass: '400 г',
          price: '1100',
        },
        {
          id: 'tsyplenyok-tapaka-na-keci',
          title: 'Цыплёнок Тапака на кеци',
          mass: '1 шт',
          price: '1410',
        },
        {
          id: 'shaurma-po-gruzinski-s-kuritsy',
          title: 'Шаурма по-грузински с курицей',
          mass: '250 г',
          price: '610',
        },
        {
          id: 'shaurma-po-gruzinski-s-telyatiny',
          title: 'Шаурма по-грузински с телятиной',
          mass: '250 г',
          price: '1100',
        },
        {
          id: 'shaurma-po-gruzinski-s-baraniny',
          title: 'Шаурма по-грузински с бараниной',
          mass: '250 г',
          price: '860',
        },
        {
          id: 'lyulya-kebab-iz-baraniny',
          title: 'Люля-кебаб из баранины',
          mass: '160 г',
          price: '1210',
        },
        {
          id: 'lyulya-kebab-iz-kuritsy',
          title: 'Люля-кебаб из курицы',
          mass: '160 г',
          price: '530',
        },
        {
          id: 'shashlyk-iz-baraniny',
          title: 'Шашлык из баранины',
          mass: '170 г',
          price: '1070',
        },
        {
          id: 'shashlyk-iz-kuritsy',
          title: 'Шашлык из курицы',
          mass: '170 г',
          price: '650',
        },
        // {
        //   id: 'koreika-teliatiny-s-baby-kartofelem',
        //   title: 'Корейка телятины с бэби-картофелем',
        //   mass: '300 г',
        //   price: '2610',
        // },
        {
          id: 'kotlety-iz-indeiki-s-piure-iz-brokkoli',
          title: 'Котлеты из индейки с пюре',
          mass: '350 г',
          price: '870',
        },
        // {
        //   id: 'koreika-teliatiny-s-ovoshchami',
        //   title: 'Корейка телятины с овощами',
        //   mass: '300 г',
        //   price: '2760',
        // },
        {
          id: 'shnitsel-po-milanski',
          title: 'Шницель по-милански',
          mass: '250 г',
          price: '990',
        },
        {
          id: 'kare-iagnionka',
          title: 'Каре ягнёнка',
          mass: '210 г',
          price: '2190',
        },
        {
          id: 'befstroganov-iz-teliatiny',
          title: 'Бефстроганов из говяжьей вырезки',
          mass: '350 г',
          price: '1490',
        },
        {
          id: 'kuritsa-teriyaki',
          title: 'Курица Терияки',
          mass: '300 г',
          price: '860',
        },
        {
          id: 'fermerskii-tsyplionok-iz-pechi',
          title: 'Фермерский цыплёнок из печи',
          mass: '1 шт',
          price: '1540',
        },
        {
          id: 'dorado-na-grile',
          title: 'Дорадо на гриле',
          mass: '1 шт',
          price: '1620',
        },
        {
          id: 'sibas-na-grile',
          title: 'Сибас на гриле',
          mass: '1 шт',
          price: '1590',
        },
        {
          id: 'steik-iz-siomgi-v-slivochnom-souse-so-shpinatom',
          title: 'Стейк из сёмги на гриле',
          mass: '200 г',
          price: '2240',
        },
        // {
        //   id: 'file-dorado-na-poduske-so-shpinatom',
        //   title: 'Филе Дорадо на подушке со шпинатом',
        //   mass: '250 г',
        //   price: '990',
        // },
        {
          id: 'penne-s-lososem-v-slivochnom-souse',
          title: 'Пенне с сёмгой в сливочном соусе',
          mass: '300 г',
          price: '1120',
        },
      ],
    },
    {
      id: 'vypechka',
      title: 'Выпечка',
      level: 1,
      children: [
        {
          id: 'khachapuri-po-adzharski',
          title: 'Хачапури по-аджарски',
          mass: '420 г|350 г',
          price: '630',
        },
        {
          id: 'khachapuri-po-imeretinski',
          title: 'Хачапури по-имеретински',
          mass: '520 г',
          price: '640',
        },
        {
          id: 'khachapuri-po-megrelski',
          title: 'Хачапури по-мегрельски',
          mass: '520 г',
          price: '690',
        },
        {
          id: 'khachapuri-so-shpinatom-i-syrom',
          title: 'Хачапури со шпинатом и сыром',
          mass: '480 г',
          price: '780',
        },
        {
          id: 'penovani',
          title: 'Пеновани',
          mass: '250 г',
          price: '590',
        },
        {
          id: 'kubdari',
          title: 'Кубдари',
          mass: '450 г',
          price: '1490',
        },
        {
          id: 'achma',
          title: 'Ачма',
          mass: '295 г',
          price: '560',
        },
        {
          id: 'mchadi-s-syrom',
          title: 'Мчади с сыром',
          mass: '255 г',
          price: '380',
        },
        {
          id: 'chvishtari',
          title: 'Чвиштари',
          mass: '200 г',
          price: '380',
        },
        {
          id: 'fokacha-po-gruzinski',
          title: 'Фокача по-грузински',
          mass: '120 г',
          price: '210',
        },
        {
          id: 'lavash',
          title: 'Лаваш',
          mass: '100 г',
          price: '170',
        },
      ],
    },
    {
      id: 'garniry',
      title: 'Гарниры',
      level: 1,
      children: [
        {
          id: 'tsukini-na-grile-paru',
          title: 'Цукини на гриле / пару',
          mass: '150 г',
          price: '430',
        },
        {
          id: 'baklazhany-na-grile-paru',
          title: 'Баклажаны на гриле / пару',
          mass: '150 г',
          price: '520',
        },
        {
          id: 'dikiy-ris',
          title: 'Дикий рис',
          mass: '150 г',
          price: '470',
        },
        {
          id: 'ovoschi-na-grile-paru',
          title: 'Овощи на гриле / пару',
          mass: '150 г',
          price: '460',
        },
        {
          id: 'kartofel-s-gribami',
          title: 'Картофель жареный с грибами',
          mass: '250 г',
          price: '390',
        },
        {
          id: 'ris-basmati',
          title: 'Рис Басмати',
          mass: '150 г',
          price: '260',
        },
        {
          id: 'shpinat-s-suluguni-na-ketsi',
          title: 'Шпинат с Сулугуни на кеци',
          mass: '210 г',
          price: '470',
        },
        {
          id: 'grechka',
          title: 'Гречка',
          mass: '150 г',
          price: '260',
        },
        {
          id: 'kartofel-fri',
          title: 'Картофель фри',
          mass: '150 г',
          price: '290',
        },
        {
          id: 'shampinony-na-grile',
          title: 'Шампиньоны на гриле',
          mass: '150 г',
          price: '350',
        },
        {
          id: 'kartofelnoe-pyure',
          title: 'Картофельное пюре',
          mass: '150 г',
          price: '310',
        },
      ],
    },
    {
      id: 'sousy',
      title: 'Соусы',
      level: 1,
      children: [
        {
          id: 'bazhe',
          title: 'Баже',
          mass: '100 г',
          price: '250',
        },
        {
          id: 'narsharab',
          title: 'Наршараб',
          mass: '50 г',
          price: '120',
        },
        {
          id: 'smetano-chesnochnyi',
          title: 'Сметано-чесночный',
          mass: '50 г',
          price: '120',
        },
        {
          id: 'smetana',
          title: 'Сметана',
          mass: '50 г',
          price: '75',
        },
        {
          id: 'adjika',
          title: 'Аджика',
          mass: '50 г',
          price: '150',
        },
        {
          id: 'satsebeli',
          title: 'Сацебели',
          mass: '50 г',
          price: '150',
        },
        {
          id: 'tkemali',
          title: 'Ткемали',
          mass: '50 г',
          price: '190',
        },
        {
          id: 'made-in-georgia',
          title: 'MADE IN GEORGIA',
          mass: '50 г',
          price: '250',
        },
        {
          id: 'maconi',
          title: 'Мацони',
          mass: '50 г',
          price: '170',
        },
      ],
    },
    {
      id: 'deserty',
      title: 'Десерты',
      level: 1,
      children: [
        {
          id: 'maconi-s-myodom-i-orekhami',
          title: 'Мацони с мёдом и орехами',
          mass: '120 г',
          price: '520',
        },
        {
          id: 'medovik',
          title: 'Медовик',
          mass: '130 г',
          price: '230',
        },
        {
          id: 'napoleon',
          title: 'Наполеон',
          mass: '120 г',
          price: '470',
        },
        {
          id: 'shtrudel',
          title: 'Штрудель',
          mass: '120 г',
          price: '390',
        },
        {
          id: 'morozhenoe-movenpick',
          title: 'Мороженое "Mövenpick" в ассортименте',
          mass: '120 г',
          price: '470',
        },
        {
          id: 'sorbet-movenpick',
          title: 'Сорбет "Mövenpick" в ассортименте',
          mass: '50 г',
          price: '380',
        },
        {
          id: 'varenye-v-assortimente',
          title: 'Варенье в ассортименте',
          mass: '50 г',
          price: '350',
        },
        {
          id: 'varenye-small',
          title: 'Варенье в ассортименте (small)',
          mass: '50 г',
          price: '200',
        },
      ],
    },
  ],
};

const menu = createSlice({
  name: 'menu',
  initialState,
});

export default menu.reducer;
